language: java

before_install:
  - chmod +x gradlew install_deps.sh
  - ./install_deps.sh

install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S

env:
  global:
    TERM=dumb

sudo: false

cache:
  directories:
    - ./libs
    - $HOME/.gradle/caches

deploy:
  provider: releases
  api-key: "e5b90da5b83aebc4f3da5c09476f27e2d9215968"
  file: "./build/libs/AgriCraft-*.jar"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
